### ISSUE TITLE
Research: New validator projection running speed is too slow

### ISSUE THREAD

**Issue by calvinaco** [crypto-com/chain-indexing#669] opened 2022-01-21 08:00 UTC
## Task Details

- Identify the reason why the projection is slow
- (Optional) Research how Cosmos can still achieve a reasonable performance
  - In case DB optimization cannot achieve a reasonable speed

## Definition of Done

- Improve the projection such that it can index Testnet within 2 days

**Comment by ysong42** [comment] 2022-01-24 07:16
Spotted one cause of the slow speed. 

It is caused by cloning the delegations table, due to a missing index. The fix is to add the missing index on the delegations table, and then the projection runs way faster than before.

**Comment by ysong42** [comment] 2022-01-26 11:07
The total sync time of testnet data at 2,665,000 is around 30 hours. Less than 2 days, good 😂 .

Below is during the local testing, I recorded some sync speed for the transaction.

> height: 4906
height: 7044 (after 60s)
speed: 35.6 blocks/second -> (if total height 2,630,000, then total sync time is 20.87 hours)

>height: 326474
height: 328263 (after 60s)
speed: 29.8 blocks/second -> (total sync time 24.3 hours)

>height: 1910761
height: 1912139
speed: 23 blocks/second -> (total sync time 31.76 hours)

**Comment by ysong42** [comment] 2022-01-27 02:34
## Summary On Running the new projection against Testnet

### Final Sync Height

![image](https://user-images.githubusercontent.com/86600130/151280134-2c223628-c9ef-4e9b-b8c1-ab07b884af8f.png)

### Last Height Performance Log

**duration** is in nanosecond, indicates the time that operation takes. 0 means it take less than 1 nanosecond.

![image](https://user-images.githubusercontent.com/86600130/151280188-58ef60a9-08a9-444f-b18b-46951ea47a1d.png)

I think this image indicating that for a normal block, biggest cost is at `CloneDelegations` and `CloneValidators`. That is creating snapshot for that block.

### Average Duration For Each Action (only counts duraion > 20 ns)

![image](https://user-images.githubusercontent.com/86600130/151281307-4cbb59f0-4bfe-46cf-b4e4-5d2a69c745f9.png)

### Average Duration For Each Action (only counts duration > 100 ns)

![image](https://user-images.githubusercontent.com/86600130/151281378-a5af9aea-da38-4f2c-9dee-425492a531e6.png)

From both the average duration images, I think it indicates that at the moment, the `CloneDelegations` and `CloneValidators` is our first choice to do optimization.

**Comment by ysong42** [comment] 2022-01-27 08:32
## Summary On Running the new projection against Mainnet

### Sync speed:
> height: 11332
height: 11735 (after 60s)
speed: 6.72 blocks/second, current highest block is 4,255,287. Let’s say 4260000 blocks in total, then 7.35 days to sync up.

> height: 19642
height: 19655 (after 60s)
speed: speed: 0.22 blocks/second, current highest block is 4,255,287. Let’s say 4260000 blocks in total, then 224 days to sync up.

So when syncing up to around 20,000 block, the speed already be very slow. Almost 5 seconds a block. And in the above calculation it will take in total 224 days to sync up all blocks.

Not to mention that the speed will be slower when the height goes up, as more delegation records need to be cloned at each height. 

### DB Folder Size
![image](https://user-images.githubusercontent.com/86600130/151320079-79820fba-0413-4530-a752-88566e8105c4.png)

I did not clean the data for `testnet`. So in total, for 20,000 blocks, it takes around `202 - 188 = 14 GB` spaces. That is 7 GB for 10k blocks. If in total we have 4,260,000 blocks, the storage for DB will take 2982 GB (In reality it will takes more, as higher block height will take more space).

**Comment by ysong42** [comment] 2022-01-29 13:26
Close this as the research is done. The following action is created in #678.

**Closed by ysong42** 2022-01-29 13:26 UTC
